service: fakeSmmtV2

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  region: eu-west-2

# you can define service wide environment variables here
  environment:
    SMMT_API_KEY: ${env:SMMT_API_KEY}

package:
  exclude:
    - test/**
    - coverage/**
    - dist/**
    - local.js

functions:
  app:
    handler: src/smmtService.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'